### ISSUE TITLE
Filter value requiring hyphen in requests is inconsistent with its facet key in responses

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/gibct-data-service#224]
With the `/v0/gi/institutions/search` resource, we get a list of countries in the `meta.facets.country` object, and `bosnia_herzegovina` is one of them. However, trying to filter with it doesn’t return any results: `/v0/institutions?country=BOSNIA_HERZEGOVINA&version=1`.

Furthermore, we convert to camelCase on the front end, so it actually removes the underscore and would get us `bosniaHerzegovina`. It seems that the filter would only work with `country=bosnia-herzegovina` (with the hyphen).

So far, this is the only example I could find, but there could potentially be more.

**Comment by mphprogrammer** [comment]
@U-DON GIDS serves a dual purpose - providing data to the Vets and producing reports for the hill. Since the VA folks use the data service to produce reports, and (I think) would want the country to appear hyphenated (BOSNIA-HERZEGOVINA), it would be best not to do this at the data level. I could convert incoming requests but would have no way of differentiating countries with hyphens and countries with spaces (e.g., 'TRINIDAD AND TOBAGO'). Just as a heads up, there are countries with unusual names such as: 'ISRAEL (JERUSALEM)', 'ISRAEL (TEL AVIV)', and 'TURKEY (EXCEPT ADANA)', but 'BOSNIA-HERZEGOVINA' is the only hyphenated one so far.

**Comment by mphprogrammer** [comment]
@saintsoup52 Any thoughts on the above?

**Comment by saintsoup52** [comment]
We use hyphens a lot in school names... so I am worried about manipulating any data before it is published.

As for the type of filter I don't feel strongly either way as long as my data sheets we publish are not affected.

**Comment by mphprogrammer** [comment]
@U-DON There are schools with hypens in their names, how do you handle that?

**Comment by U-DON** [comment]
@mphprogrammer Handle that where or in doing what? We just fetch school data provided in the API responses. AFAIK, we don't need to pass the school names with hyphens into any requests like we do when filtering on country names.

**Comment by U-DON** [comment]
Also, the school names aren't used as object keys in the API responses, whereas the country names are (in the `meta.facets.country` object). I've only seen the school names as values in the JSON, and they don't undergo any case conversions, because typically values are just taken as is. Keys are the ones being transformed. So we end up using the school names with hyphens just as they are without any modifications.

**Comment by patrickvinograd** [comment]
We had to go through some similar gymnastics to make the facility locator API not get screwed up by this - a similar case where data presented in the API would be fed back as filter parameters and needed to not get changed. We wound up changing the API JSON format so that the filter values would show  up as dict values instead of keys, which was pretty awkward. 

If I understand correctly, we can set ActiveModelSerializer to leave keys unaltered - which would leave `BOSNIA-HERZEGOVINA` as-is. The other side-effect is that it would also leave other keys/facets as uppercase that are currently getting downcased. We would need to do the same in vets-api, which we can do on a per-render basis so it wouldn't have to affect the rest of vets-api. Then if keys are uppercase/dashed, it's not clear whether the CamelCase conversion in the frontend will still mess with them, or if it only touches things that are snake_cased.

**Comment by patrickvinograd** [comment]
Other countries with spaces, parens, etc, seem unaffected by the ActiveModelSerializer.

**Comment by mphprogrammer** [comment]
As far as I can see, only country would be relevant. Currently the serializer downcases and changes hyphens to underscores. We can just override the getter to leave hyphens unchanged.

**Comment by mphprogrammer** [comment]
@U-DON @saintsoup52 @saneshark This issue stems from the active_model_serializer initializer. Specifically, it sets  
```
ActiveModelSerializers.config.key_transform = :underscore
```
Which is the line responsible for converting dashes in :country in facets to underscores. Changing this to

```
ActiveModelSerializers.config.key_transform = :dash
```

Fixes the country issue but would also affect keys such as caution flag reason (e.g. `caution-flag-reason`. @saintsoup52 - none of this affects the data dashboard ....

So, options seem to be:
1. Serialize the data and meta before calling render and reconverting underscores to dashes in meta.facets.country. 
2. Change the serializer initializer
3. Change the returned meta.facets.country in vets-api
4. Change the returned meta.facets.country in vets-website

Suggestions?

**Comment by saintsoup52** [comment]
If it doesn't affect school names or the data dashboards then I will let you guys figure this out. 

I have love lost for dashes... they have the bane of my existence in the school name column of WEAMS.

**Comment by saneshark** [comment]
@mphprogrammer - 

Option 5. Leave the country keys exactly as they are currently (or normalize them in such a way that the keys can remain agnostic of :dash, camel, :snake -- this is important because of olive_branch gem), and add a "human readable" key: value pair within the country object. 

Option 6. Leave the country keys exactly as they are currently (or normalize them in such a way that the keys can remain agnostic of :dash, camel, :snake -- this is important because of olive_branch gem),
and add a separate "countries" endpoint that returns a mapping of the country keys to their human readable counter part (if Option 5 is not applicable because country is not a JSON object or something).

**Comment by patrickvinograd** [comment]
7. Change the facet structure so country names are only ever JSON object values, not keys. So instead of:

```
"facets":
   ... 
   "country":{"bosnia_herzegovina":1},
```
Make it like so:
```
"facets":
   ... 
   "country":{"name": "bosnia-herzegovina", "count": 1},
```
Might want to do this across the board for all facets so that processing it into the filter UI is consistent, even though countries are likely the only case we have where the current key names have this issue.

**Comment by patrickvinograd** [comment]
Above option will work because ActiveModel::Serializer and olive branch only permute JSON keys, not values.

**Comment by saneshark** [comment]
I think I like @patrickvinograds suggestion the most, but come to think of it shouldn't each country also have a unique id and type to conform to JSONAPI spec?

Making the country name a value vs key might make doing hash based lookup more challenging is the only drawback of this approach that I can think of. Should be relatively easy to transpose values to keys if someone needs O(1) lookup though.

Answer comes down to how is it being consumed, simply presentation, lookup, both?

**Comment by patrickvinograd** [comment]
If the countries were API-addressable objects in the REST sense then they'd need an ID and type - but in this proposal they aren't - there are no CRUD operations on country objects.  They're just strings that can be displayed in the search results UI and then fed back as filter query parameters for a subsequent search.

**Comment by saneshark** [comment]
I don't think JSONAPI technically supports any alternative to an id and type based object looking at the specs.

**Comment by saneshark** [comment]
I've been calculating an MD5 checksum of the JSON body and assigning that as id

**Comment by saneshark** [comment]
@U-DON I think what @patrickvinograd is proposing here could work, but I'm concerned because the JSON object would be changing somewhat considerably from what it is currently. This will obviously require a corresponding change to how you parse the object components.

Do you currently just load the all the values or are you targeting specific countries using a key based lookup? If so, I think my proposal of having a "human_readable" key would likely be sufficient with least amount of impact. Thoughts?

Let us discuss this briefly after standup and make sure we're tracking this. We should ideally try to have a PR out for this on the backend tonight, and a PR for it on the Front-end by tomorrow morning if possible.

**Comment by U-DON** [comment]
Currently just loading all the keys provided from `meta.facets.country` and then listing them as options in a dropdown. The values there are being used for the search filter params and nothing else.

**Comment by saneshark** [comment]
option 7 it is.

**Comment by U-DON** [comment]
To clarify, that option would mean that `meta.facets.country` would be a list of objects, right? Something like:

```
country: [
    { name: 'country name 1', count: 123 },
    { name: 'country name 2', count: 456 },
    ...
]
```

**Comment by patrickvinograd** [comment]
Yes.
