### ISSUE TITLE
What does "generate new preview version" do?

### ISSUE THREAD

**Issue by saintsoup52** [department-of-veterans-affairs/gibct-data-service#254]
In the old GIDS uploaded files were not merged into the bigger institution until a user told the DS to merge all the files together. The purpose, as I understood it, was so that if a file was uploaded that had errors there would be a chance to do it again before merging it all together.

However, now the "generate new preview version" is now in a different place and has a user warning that says, "Are you sure?"

![image](https://cloud.githubusercontent.com/assets/4397508/24956358/3e447d52-1f55-11e7-99c0-59ae662eb8a0.png)

![image](https://cloud.githubusercontent.com/assets/4397508/24956392/660d88ba-1f55-11e7-918b-ca9890692a6e.png)

At what point are CSVs merged into the larger institution file? And if it is when you select this "generate new preview version" button shouldn't it be up with the other three action buttons?

![image](https://cloud.githubusercontent.com/assets/4397508/24956435/a37ed640-1f55-11e7-953a-e3d7000914cf.png)

@mphprogrammer @saneshark

**Comment by saintsoup52** [comment]
It appears pushing this button is a critical step in the process because the version is not updating after I load a CSV and pushing one of the action buttons.

if this is the case is should be put next to the action buttons.

**Comment by patrickvinograd** [comment]
Yes, "Generate Preview" merges any newly-uploaded CSVs into the institution table.

I think Kam avoided putting it directly with those three buttons because those three buttons belong to the specific preview version, and generating a new preview is not in the scope of the current preview version. 

I think a better place is right next to the "Latest Preview Version" subhead. I.e move it from next to "Latest Uploads" to "Latest Preview Version".

**Comment by saintsoup52** [comment]
The problem is that after a user uploads a CSV the expectation is that it would be included in the staging site, however that only happens when you click that button.

So it is actually a required step in the process... it actually merges the file.

**Comment by mphprogrammer** [comment]
Its the same as "Push Data to Gibct Preview" just different wording

**Comment by saneshark** [comment]
@patrickvinograd I think the butotn should be near the Latest Uploads to draw attention to the fact that it is a next step after making uploads. 

@saintsoup52 because the generating of institutions takes some time, we're allowing users to upload N number of CSV before generating a preview version. Hence the need for the button. We are proposing an improvement to disable the button when the created_at date of all uploads <= the created_at of the current preview version.

We can also update the confirm dialog to be something more descriptive "Are you sure you want to create a new preview version?" would probably be better than "are you sure?"

**Comment by saneshark** [comment]
This ticket partially overlaps with: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/2111

**Comment by saneshark** [comment]
I say partially because the inclusion of the language proposed above for the confirmation is not detailed in that ticket.

**Comment by patrickvinograd** [comment]
Also button placement. Maybe Mel should be the decider on that one :)

**Comment by saintsoup52** [comment]
In the old version the buttons in the left hand corner were in order of the steps a user would normally go through to update the tool. That was very intuitive, this order is the opposite. Especially when it is not entirely clear that by not pushing that button the tool never really updates.

**Comment by saneshark** [comment]
@saintsoup52 I'm going to respectfully disagree with you here. The new user interface has the actions available to be performed broken down into the individual subsections of the dashboard. The dashboard is one-stop-shop for everything and Preview versions and Production versions are very well dilineated. There is even logic that will be going into affect that will disable (not hide) buttons based on context.

I would sooner add helpful comments to the introduction text at the top than go back to the old UI design.

**Comment by saneshark** [comment]
But I will defer to @melwoodard

**Comment by saneshark** [comment]
@saintsoup52 additional context: in future iteration we will be introducing the ability to rollback production versions, and possibly even viewing versions that are not the current preview version. Given that context the old user interface would not make any sense.

**Comment by melwoodard** [comment]
I think @patrickvinograd's proposal to move the "generate preview" button up next to the "Latest Preview Version" heading makes sense. That way all the actions related to preview are in the same area, and likewise the actions in the Uploads section are only related to uploads.
